meta_product_name: "BonjourHi"
meta_title: "BonjourHi - I speak your language, you speak mine"
meta_description: "Cool free app that connects language partners who want to casually meet in person and improve each other’s foreign language skills."
meta_image: "logo.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
